{% set name = "basis_set_exchange" %}
{% set version = "0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80f89348e4cc52b12f89391f923564eb5f877e316e2f8fe1e4f28df769d2c852

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bse=basis_set_exchange.cli:run_bse_cli
    - bsecurate=basis_set_exchange.cli:run_bsecurate_cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools-scm >=8.0
  run:
    - python >={{ python_min }}
    - jsonschema
    - argcomplete
    - regex
    - unidecode

test:
  imports:
    - basis_set_exchange
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - bse -h
    - bsecurate -h
    - test -f $SP_DIR/basis_set_exchange/__init__.py
    - pip check
    - python -c "import basis_set_exchange as qc;print(qc.__version__);assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"

about:
  home: https://github.com/MolSSI-BSE/basis_set_exchange
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A repository for quantum chemistry basis sets
  doc_url: https://molssi-bse.github.io/basis_set_exchange/
  dev_url: https://github.com/MolSSI-BSE/basis_set_exchange

extra:
  recipe-maintainers:
    - mattwthompson
    - bennybp
