{% set name = "basis_set_exchange" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1100c17821292fba94e30a0bf646e7a8ce362f9ef80de994185fe1c921aa487

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bse=basis_set_exchange.cli:run_bse_cli
    - bsecurate=basis_set_exchange.cli:run_bsecurate_cli

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - jsonschema
    - argcomplete
    - regex

test:
  imports:
    - basis_set_exchange
  commands:
    - bse -h
    - bsecurate -h

about:
  home: https://github.com/MolSSI-BSE/basis_set_exchange
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A repository for quantum chemistry basis sets
  doc_url: https://molssi-bse.github.io/basis_set_exchange/
  dev_url: https://github.com/MolSSI-BSE/basis_set_exchange

extra:
  recipe-maintainers:
    - mattwthompson
    - bennybp
